device: 
  value: cuda:0
task_name:
  value: tSOPHON
domain_src:
  value: rmt0
domain_tgt:
  value: rmt45
image_size:
  value: 64
num_classes:
  value: 10
seed:
  value: 2023
batch_size:
  value: 128
num_workers:
  value: 4
pre_split:
  value: True
data_transform:
  value: ntl
teacher_network:
  value: resnet18
teacher_pretrain:
  value: True
train_teacher_scratch:
  value: True
save_train_teacher:
  value: True
pretrained_teacher:
  value: auto
pretrain_epochs:
  value: 20
pretrain_lr:
  value: 0.01 
SOPHON_ways:
  value: 10
SOPHON_total_loop:
  value: 1000
pretrain_momentum:
  value: 0.9
pretrain_weight_decay:
  value: 0.0001
#########################################
# additional parameters for CUTI-domain
#########################################
CUTI_alpha:
  value: 0.1

#########################################
# additional parameters for HNTL
#########################################
HNTL_adapt_pooling:
  value: True
HNTL_rec_coef:
  value: 0.1
HNTL_lambda_vae:
  value: 0.001
HNTL_lambda_disent:
  value: 0.08
HNTL_student_pretrain:
  value: True
# stage 1: Disentanglement
HNTL_Disen_epochs:
  value: 30
HNTL_Disen_lr:
  value: 0.001
HNTL_Disen_momentum:
  value: 0.9
HNTL_Disen_weight_decay:
  value: 0.0001
# stage 2: Knowledge Distillation
HNTL_KD_epochs:
  value: 20
HNTL_KD_lr:
  value: 0.001
HNTL_KD_momentum:
  value: 0.9
HNTL_KD_weight_decay:
  value: 0.0001
#########################################
# additional parameters for SOPHON
#########################################
SOPHON_ways:
  value: 10  # 注意：PACS是7，OfficeHome是65，请根据数据集修改这个值！
SOPHON_total_loop:
  value: 2000
SOPHON_ml_loop:
  value: 1
SOPHON_nl_loop:
  value: 1
SOPHON_fast_lr:
  value: 0.0001
SOPHON_lr:
  value: 0.0001
SOPHON_alpha:
  value: 3.0
SOPHON_beta:
  value: 5.0
SOPHON_adaptation_steps:
  value: 50
SOPHON_maml_loss_func:
  value: 'kl_loss'